spring.application.name=file-service
server.port=8086

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/msvcaws-usergestion

#ESTAS SERAN LAS CREDICIALES EN AWS asi como se ve
spring.datasource.username=postgres
spring.datasource.password=12345
spring.jpa.hibernate.ddl-auto=create-drop

eureka.client.serviceUrl.defaultZone=http://user:password@localhost:8761/eureka
eureka.instance.preferIpAddress=true

resilience4j.circuitbreaker.instances.appfile.register-health-indicator=true
resilience4j.circuitbreaker.instances.appfile.event-consumer-buffer-size=10
resilience4j.circuitbreaker.instances.appfile.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.appfile.sliding-window-size=5
resilience4j.circuitbreaker.instances.appfile.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.appfile.waitDurationInOpenState= 5s
resilience4j.circuitbreaker.instances.appfile.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.appfile.automatic-transition-from-open-to-half-open-enabled=true

spring.zipkin.base-url=http://localhost:9411
management.tracing.sampling.probability=1.0

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.template.default-topic=notificationTopic
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
#Indica que se va usar StringSerializer para serializar
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.type.mapping=TransactionPlacedEvent:com.msvc_aws.proyecto00.file_service.event.TransactionPlacedEvent

#Indica el tipo de mensaje

management.endpoints.web.exposure.include=*
management.endpoint.prometheus.enabled=true
